"""Install bundle-required Python interpreters without touching system packages."""

from __future__ import annotations

import os
import platform
import re
import shutil
import subprocess
import sys
import tarfile
import time
from pathlib import Path

from flashcli import config
from flashcli.bundle.python_standalone_hub import (
    download_standalone_asset,
    resolve_standalone_asset,
)
from flashcli.standalone_release import DEFAULT_STANDALONE_TAG

_ENV_LOADED = False
_STANDALONE_TAG = os.environ.get("FLASHCLI_PYTHON_STANDALONE_TAG", DEFAULT_STANDALONE_TAG)


def bundle_python_root() -> Path:
    """User-writable prefix for standalone Python (default ``~/.flashcli/python``)."""
    override = os.environ.get("FLASHCLI_PYTHON_ROOT", "").strip()
    if override:
        return Path(override).expanduser()
    return config.FLASHCLI_HOME / "python"


def bundle_python_env_file() -> Path:
    override = os.environ.get("FLASHCLI_PYTHON_ENV", "").strip()
    if override:
        return Path(override).expanduser()
    return config.FLASHCLI_HOME / "python-runtime.env"


def auto_install_bundle_python_enabled() -> bool:
    raw = os.environ.get("FLASHCLI_AUTO_INSTALL_BUNDLE_PYTHON", "1").strip().lower()
    return raw not in ("0", "false", "no", "off")


def load_python_env_file() -> None:
    """Load ``FLASHCLI_PY*_BIN`` from the runtime env file (does not override env)."""
    global _ENV_LOADED
    if _ENV_LOADED:
        return
    path = bundle_python_env_file()
    if path.is_file():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("export "):
                line = line[7:].strip()
            if "=" not in line:
                continue
            key, _, val = line.partition("=")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            if key.startswith("FLASHCLI_PY") and key.endswith("_BIN") and val:
                os.environ.setdefault(key, val)
    _ENV_LOADED = True


def _py_mm(py_minor: str) -> str:
    return f"{py_minor[0]}.{py_minor[1:]}"


def _standalone_triplet() -> str:
    machine = platform.machine().lower()
    if sys.platform == "linux":
        if machine in ("x86_64", "amd64"):
            return "x86_64-unknown-linux-gnu"
        if machine in ("aarch64", "arm64"):
            return "aarch64-unknown-linux-gnu"
    if sys.platform == "darwin":
        if machine in ("arm64", "aarch64"):
            return "aarch64-apple-darwin"
        if machine in ("x86_64", "amd64"):
            return "x86_64-apple-darwin"
    raise RuntimeError(
        f"Standalone Python install is not supported on {sys.platform}/{platform.machine()}. "
        f"Install Python manually and set FLASHCLI_PY{{minor}}_BIN."
    )


def standalone_download_url(py_minor: str, *, tag: str | None = None) -> str:
    """Return the python-build-standalone tarball URL for *py_minor* (``312`` → 3.12)."""
    if not py_minor.isdigit() or len(py_minor) != 3:
        raise ValueError(f"Invalid python minor tag: {py_minor!r}")
    asset = resolve_standalone_asset(
        py_minor,
        _standalone_triplet(),
        tag=tag or _STANDALONE_TAG,
    )
    return asset.url


def _python_reports_minor(py_bin: Path, py_minor: str) -> bool:
    try:
        out = subprocess.run(
            [str(py_bin), "-c", "import sys; print(sys.version_info[:2])"],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    if out.returncode != 0:
        return False
    m = re.match(r"\((\d+), (\d+)\)", out.stdout.strip())
    if not m:
        return False
    return int(m.group(1)) == int(py_minor[0]) and int(m.group(2)) == int(py_minor[1:])


def _installed_standalone_bin(dest: Path, py_minor: str) -> Path | None:
    mm = _py_mm(py_minor)
    for name in (f"python{mm}", "python3", "python"):
        candidate = dest / "bin" / name
        if candidate.is_file() and os.access(candidate, os.X_OK):
            if _python_reports_minor(candidate, py_minor):
                return candidate.resolve()
    return None


def _register_python_bin(py_minor: str, py_bin: Path) -> None:
    var = f"FLASHCLI_PY{py_minor}_BIN"
    os.environ[var] = str(py_bin)
    env_path = bundle_python_env_file()
    env_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    if env_path.is_file():
        lines = env_path.read_text(encoding="utf-8").splitlines()
    prefix = f"export {var}="
    lines = [ln for ln in lines if not ln.strip().startswith(prefix)]
    lines.append(f"export {var}={py_bin}")
    env_path.write_text(
        "# Generated by flashcli — bundle runtime Python interpreters\n"
        + "\n".join(lines)
        + "\n",
        encoding="utf-8",
    )


def install_standalone_python(
    py_minor: str,
    *,
    quiet: bool = False,
    force: bool = False,
) -> Path:
    """Download and extract python-build-standalone under ``bundle_python_root()``."""
    if not py_minor.isdigit() or len(py_minor) != 3:
        raise ValueError(f"Invalid python minor tag: {py_minor!r}")

    root = bundle_python_root()
    mm = _py_mm(py_minor)
    dest = root / mm
    if not force:
        existing = _installed_standalone_bin(dest, py_minor)
        if existing is not None:
            return existing

    root.mkdir(parents=True, exist_ok=True)
    cache_dir = root / ".cache"
    cache_dir.mkdir(parents=True, exist_ok=True)
    tarball = cache_dir / f"cpython-{mm}-{_STANDALONE_TAG}.tar.gz"
    asset = resolve_standalone_asset(
        py_minor,
        _standalone_triplet(),
        tag=_STANDALONE_TAG,
        quiet=quiet,
    )

    lock = cache_dir / f"install-{py_minor}.lock"
    deadline = time.monotonic() + 900
    while lock.exists() and time.monotonic() < deadline:
        existing = _installed_standalone_bin(dest, py_minor)
        if existing is not None:
            return existing
        time.sleep(2)
    if lock.exists():
        raise RuntimeError(
            f"Timed out waiting for Python {mm} install lock ({lock}). "
            "Remove the lock file if no other flashcli process is installing."
        )

    try:
        lock.write_text(f"{os.getpid()}\n", encoding="utf-8")
        if not tarball.is_file():
            if not quiet:
                print(
                    f"Installing Python {mm} for bundle runtime "
                    f"(standalone → {dest}) …",
                    file=sys.stderr,
                )
            download_standalone_asset(
                asset,
                tarball,
                quiet=quiet,
            )
        if dest.is_dir():
            shutil.rmtree(dest)
        dest.mkdir(parents=True, exist_ok=True)
        extract_kw: dict[str, object] = {}
        if sys.version_info >= (3, 12):
            extract_kw["filter"] = "data"
        with tarfile.open(tarball, "r:gz") as archive:
            members: list[tarfile.TarInfo] = []
            for member in archive.getmembers():
                if member.name == "python" or member.name.startswith("python/"):
                    suffix = member.name[len("python") :].lstrip("/")
                    if not suffix:
                        continue
                    member = member.replace(name=suffix)
                    members.append(member)
            archive.extractall(dest, members=members, **extract_kw)  # type: ignore[arg-type]

        py_bin = _installed_standalone_bin(dest, py_minor)
        if py_bin is None:
            raise RuntimeError(f"Standalone extract failed under {dest}/bin")

        link = dest / "bin" / f"python{mm}"
        if not link.exists():
            link.symlink_to(py_bin.name)

        _register_python_bin(py_minor, py_bin)
        if not quiet:
            print(f"Installed Python {mm}: {py_bin}", file=sys.stderr)
        return py_bin
    finally:
        lock.unlink(missing_ok=True)


def ensure_python_for_minor(
    py_minor: str,
    *,
    quiet: bool = False,
    auto_install: bool | None = None,
) -> Path | None:
    """Resolve or auto-install the Python interpreter for bundle *py_minor* (``312``)."""
    from flashcli.bundle.python_resolve import resolve_python_for_minor

    load_python_env_file()
    found = resolve_python_for_minor(py_minor, require_venv=True)
    if found is not None:
        return found

    do_install = (
        auto_install_bundle_python_enabled()
        if auto_install is None
        else auto_install
    )
    if not do_install:
        return None

    try:
        return install_standalone_python(py_minor, quiet=quiet)
    except Exception as exc:
        mm = _py_mm(py_minor)
        raise RuntimeError(
            f"Failed to auto-install Python {mm} under {bundle_python_root()}: {exc}"
        ) from exc
