#!/usr/bin/env bash
# Install flashcli-go from release binaries (github/gitee), verify sha256, and
# place it on PATH. Companion to install.sh (Python host); does not install
# Python. Bundle venvs still get flashcli-bundle[infer] on demand.
#
# Usage:
#   curl -fsSL .../scripts/install_go.sh | sh
#   FLASHCLI_GO_VERSION=0.3.3 sh scripts/install_go.sh --mirror
set -euo pipefail

REPO_GITHUB="aodianyun/flashcli"
REPO_GITEE="aodiansoft/flashcli"
VERSION="${FLASHCLI_GO_VERSION:-latest}"
USE_MIRROR="${FLASHCLI_USE_MIRROR:-0}"
INSTALL_DIR="${FLASHCLI_GO_INSTALL_DIR:-}"

while [ $# -gt 0 ]; do
  case "$1" in
    --mirror|--gitee) USE_MIRROR=1 ;;
    --github) USE_MIRROR=0 ;;
    --version) VERSION="$2"; shift ;;
    --dir) INSTALL_DIR="$2"; shift ;;
    -h|--help)
      echo "usage: install_go.sh [--mirror] [--version V] [--dir DIR]"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch="$(uname -m)"
case "$arch" in
  x86_64|amd64) arch="amd64" ;;
  aarch64|arm64) arch="arm64" ;;
  *) echo "unsupported arch: $arch" >&2; exit 1 ;;
esac
case "$os" in
  linux|darwin) ;;
  *) echo "unsupported OS: $os" >&2; exit 1 ;;
esac

asset="flashcli-${os}-${arch}"

if [ -n "$INSTALL_DIR" ]; then
  dest="$INSTALL_DIR"
elif [ -w /usr/local/bin ]; then
  dest="/usr/local/bin"
else
  dest="$HOME/.local/bin"
fi
mkdir -p "$dest"

if [ "$USE_MIRROR" = "1" ]; then
  api="https://gitee.com/api/v5/repos/${REPO_GITEE}/releases/latest"
  base="https://gitee.com/${REPO_GITEE}/releases/download"
else
  api="https://api.github.com/repos/${REPO_GITHUB}/releases/latest"
  base="https://github.com/${REPO_GITHUB}/releases/download"
fi

if [ "$VERSION" = "latest" ]; then
  if command -v curl >/dev/null 2>&1; then
    VERSION="$(curl -fsSL "$api" | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"v\{0,1\}\([^"]*\)".*/\1/p' | head -1)"
  elif command -v wget >/dev/null 2>&1; then
    VERSION="$(wget -qO- "$api" | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"v\{0,1\}\([^"]*\)".*/\1/p' | head -1)"
  fi
  [ -n "$VERSION" ] || { echo "error: cannot resolve latest version" >&2; exit 1; }
fi
echo "installing flashcli-go ${VERSION} (${os}/${arch}) ..."

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

fetch() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$1" -o "$2"
  else
    wget -qO "$2" "$1"
  fi
}

fetch "${base}/v${VERSION}/${asset}" "$tmp/$asset"
fetch "${base}/v${VERSION}/sha256sums.txt" "$tmp/sha256sums.txt"

want="$(awk -v a="$asset" '$2==a {print $1}' "$tmp/sha256sums.txt" | head -1)"
[ -n "$want" ] || { echo "error: $asset not found in sha256sums.txt" >&2; exit 1; }

if command -v sha256sum >/dev/null 2>&1; then
  have="$(sha256sum "$tmp/$asset" | awk '{print $1}')"
else
  have="$(shasum -a 256 "$tmp/$asset" | awk '{print $1}')"
fi
if [ "$have" != "$want" ]; then
  echo "error: checksum mismatch for $asset" >&2
  echo "  have: $have" >&2
  echo "  want: $want" >&2
  exit 1
fi

install -m 0755 "$tmp/$asset" "$dest/flashcli"
echo "[ok] installed $dest/flashcli"

# Persist source hints so bundle venvs can install flashcli-bundle[infer].
home="${FLASHCLI_HOME:-$HOME/.flashcli}"
mkdir -p "$home" 2>/dev/null || true
{
  echo "# Generated by install_go.sh"
  echo "export FLASHCLI_INSTALL_HOST=go"
  if [ "$USE_MIRROR" = "1" ]; then
    echo "export FLASHCLI_INSTALL_REPO=https://gitee.com/aodiansoft/flashcli.git"
  else
    echo "export FLASHCLI_INSTALL_REPO=https://github.com/aodianyun/flashcli.git"
  fi
  echo "export FLASHCLI_INSTALL_REF=${FLASHCLI_INSTALL_REF:-main}"
} > "$home/install.env" 2>/dev/null || true

case ":$PATH:" in
  *":$dest:"*) ;;
  *) echo "note: add $dest to PATH" ;;
esac
